# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: "http://xugang.ink"
date_format: "ordinal"
title: Sugar
subtitle: "论人类知识之盲点"
description: "徐刚的个人博客"
keywords: 
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: xugang
organization: Tongji University
organization_url: 
github_username: xugangtongji
location: Shanghai, China
email: 1631558@tongji.edu.cn

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 项目

  -
    href: /links/
    label: 相册

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: xugangtongji/xugangtongji.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: xugangtongji
    repo: xugangBlog
    oauth:
        client_id: 45090f27112e5e1719eb
        client_secret: b855edadf40ebd1fa4c4cb3c52c6972541e3574d
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: xugangtongji
    repo: xugangBlog
    clientID: 45090f27112e5e1719eb
    clientSecret: b855edadf40ebd1fa4c4cb3c52c6972541e3574d
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

